routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');

Route::resource('users', 'UserController');

Route::resource('languages', 'LanguageController');

Route::resource('countries', 'CountryController');

Route::resource('cities', 'CityController');

Route::resource('stores', 'StoreController');

Route::resource('storeLangs', 'StoreLangController');

Route::resource('categories', 'CategoryController');

Route::resource('categoryLanguages', 'CategoryLanguageController');

Route::resource('products', 'ProductController');

Route::resource('productLangs', 'ProductLangController');

Route::resource('productStores', 'ProductStoreController');

Route::resource('productGalleries', 'ProductGalleryController');

Route::resource('favourites', 'FavouriteController');

Route::resource('questions', 'QuestionController');

Route::resource('answers', 'AnswerController');

Route::resource('offers', 'OfferController');

Route::resource('news', 'NewsController');

Route::resource('cobons', 'CobonsController');

Route::resource('sliders', 'SliderController');

Route::resource('sliderLangs', 'SliderLangController');

Route::resource('settings', 'SettingController');

app/Models/ProductLang.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ProductLang
 * @package App\Models
 * @version February 26, 2020, 11:06 am UTC
 *
 * @property \App\Models\Language lang
 * @property \App\Models\Product product
 * @property integer product_id
 * @property integer lang_id
 * @property string name
 * @property string description
 * @property string details
 */
class ProductLang extends Model
{
    use SoftDeletes;

    public $table = 'product_langs';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'product_id',
        'lang_id',
        'name',
        'description',
        'details'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'product_id' => 'integer',
        'lang_id' => 'integer',
        'name' => 'string',
        'description' => 'string',
        'details' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'product_id' => 'required',
        'lang_id' => 'required',
        'name' => 'required',
        'description' => 'required',
        'details' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function lang()
    {
        return $this->belongsTo(\App\Models\Language::class, 'lang_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function product()
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id');
    }
}

app/Http/Controllers/ProductLangController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ProductLangDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateProductLangRequest;
use App\Http\Requests\UpdateProductLangRequest;
use App\Repositories\ProductLangRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ProductLangController extends AppBaseController
{
    /** @var  ProductLangRepository */
    private $productLangRepository;

    public function __construct(ProductLangRepository $productLangRepo)
    {
        $this->productLangRepository = $productLangRepo;
    }

    /**
     * Display a listing of the ProductLang.
     *
     * @param ProductLangDataTable $productLangDataTable
     * @return Response
     */
    public function index(ProductLangDataTable $productLangDataTable)
    {
        return $productLangDataTable->render('product_langs.index');
    }

    /**
     * Show the form for creating a new ProductLang.
     *
     * @return Response
     */
    public function create()
    {
        return view('product_langs.create');
    }

    /**
     * Store a newly created ProductLang in storage.
     *
     * @param CreateProductLangRequest $request
     *
     * @return Response
     */
    public function store(CreateProductLangRequest $request)
    {
        $input = $request->all();

        $productLang = $this->productLangRepository->create($input);

        Flash::success('Product Lang saved successfully.');

        return redirect(route('productLangs.index'));
    }

    /**
     * Display the specified ProductLang.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $productLang = $this->productLangRepository->find($id);

        if (empty($productLang)) {
            Flash::error('Product Lang not found');

            return redirect(route('productLangs.index'));
        }

        return view('product_langs.show')->with('productLang', $productLang);
    }

    /**
     * Show the form for editing the specified ProductLang.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $productLang = $this->productLangRepository->find($id);

        if (empty($productLang)) {
            Flash::error('Product Lang not found');

            return redirect(route('productLangs.index'));
        }

        return view('product_langs.edit')->with('productLang', $productLang);
    }

    /**
     * Update the specified ProductLang in storage.
     *
     * @param  int              $id
     * @param UpdateProductLangRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProductLangRequest $request)
    {
        $productLang = $this->productLangRepository->find($id);

        if (empty($productLang)) {
            Flash::error('Product Lang not found');

            return redirect(route('productLangs.index'));
        }

        $productLang = $this->productLangRepository->update($request->all(), $id);

        Flash::success('Product Lang updated successfully.');

        return redirect(route('productLangs.index'));
    }

    /**
     * Remove the specified ProductLang from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $productLang = $this->productLangRepository->find($id);

        if (empty($productLang)) {
            Flash::error('Product Lang not found');

            return redirect(route('productLangs.index'));
        }

        $this->productLangRepository->delete($id);

        Flash::success('Product Lang deleted successfully.');

        return redirect(route('productLangs.index'));
    }
}

resources/views/product_langs/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Lang
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'productLangs.store']) !!}

                        @include('product_langs.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product_langs/datatables_actions.blade.php
{!! Form::open(['route' => ['productLangs.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('productLangs.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('productLangs.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/product_langs/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Lang
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($productLang, ['route' => ['productLangs.update', $productLang->id], 'method' => 'patch']) !!}

                        @include('product_langs.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/product_langs/fields.blade.php
<!-- Product Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('product_id', 'Product Id:') !!}
    {!! Form::number('product_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Lang Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lang_id', 'Lang Id:') !!}
    {!! Form::number('lang_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Details Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('details', 'Details:') !!}
    {!! Form::textarea('details', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('productLangs.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/product_langs/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Product Langs</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('productLangs.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('product_langs.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/product_langs/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Lang
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('product_langs.show_fields')
                    <a href="{{ route('productLangs.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product_langs/show_fields.blade.php
<!-- Product Id Field -->
<div class="form-group">
    {!! Form::label('product_id', 'Product Id:') !!}
    <p>{{ $productLang->product_id }}</p>
</div>

<!-- Lang Id Field -->
<div class="form-group">
    {!! Form::label('lang_id', 'Lang Id:') !!}
    <p>{{ $productLang->lang_id }}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $productLang->name }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $productLang->description }}</p>
</div>

<!-- Details Field -->
<div class="form-group">
    {!! Form::label('details', 'Details:') !!}
    <p>{{ $productLang->details }}</p>
</div>

resources/views/product_langs/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush