routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');

Route::resource('users', 'UserController');

Route::resource('languages', 'LanguageController');

Route::resource('countries', 'CountryController');

Route::resource('cities', 'CityController');

Route::resource('stores', 'StoreController');

Route::resource('storeLangs', 'StoreLangController');

Route::resource('categories', 'CategoryController');

Route::resource('categoryLanguages', 'CategoryLanguageController');

Route::resource('products', 'ProductController');

Route::resource('productLangs', 'ProductLangController');

Route::resource('productStores', 'ProductStoreController');

Route::resource('productGalleries', 'ProductGalleryController');

Route::resource('favourites', 'FavouriteController');

Route::resource('questions', 'QuestionController');

Route::resource('answers', 'AnswerController');

Route::resource('offers', 'OfferController');

Route::resource('news', 'NewsController');

Route::resource('cobons', 'CobonsController');

Route::resource('sliders', 'SliderController');

Route::resource('sliderLangs', 'SliderLangController');

Route::resource('settings', 'SettingController');

app/Models/ProductGallery.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ProductGallery
 * @package App\Models
 * @version February 26, 2020, 11:07 am UTC
 *
 * @property \App\Models\Product product
 * @property integer product_id
 * @property string video
 * @property string img
 */
class ProductGallery extends Model
{
    use SoftDeletes;

    public $table = 'product_galleries';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'product_id',
        'video',
        'img'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'product_id' => 'integer',
        'video' => 'string',
        'img' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'product_id' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function product()
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id');
    }
}

app/Http/Controllers/ProductGalleryController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ProductGalleryDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateProductGalleryRequest;
use App\Http\Requests\UpdateProductGalleryRequest;
use App\Repositories\ProductGalleryRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ProductGalleryController extends AppBaseController
{
    /** @var  ProductGalleryRepository */
    private $productGalleryRepository;

    public function __construct(ProductGalleryRepository $productGalleryRepo)
    {
        $this->productGalleryRepository = $productGalleryRepo;
    }

    /**
     * Display a listing of the ProductGallery.
     *
     * @param ProductGalleryDataTable $productGalleryDataTable
     * @return Response
     */
    public function index(ProductGalleryDataTable $productGalleryDataTable)
    {
        return $productGalleryDataTable->render('product_galleries.index');
    }

    /**
     * Show the form for creating a new ProductGallery.
     *
     * @return Response
     */
    public function create()
    {
        return view('product_galleries.create');
    }

    /**
     * Store a newly created ProductGallery in storage.
     *
     * @param CreateProductGalleryRequest $request
     *
     * @return Response
     */
    public function store(CreateProductGalleryRequest $request)
    {
        $input = $request->all();

        $productGallery = $this->productGalleryRepository->create($input);

        Flash::success('Product Gallery saved successfully.');

        return redirect(route('productGalleries.index'));
    }

    /**
     * Display the specified ProductGallery.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $productGallery = $this->productGalleryRepository->find($id);

        if (empty($productGallery)) {
            Flash::error('Product Gallery not found');

            return redirect(route('productGalleries.index'));
        }

        return view('product_galleries.show')->with('productGallery', $productGallery);
    }

    /**
     * Show the form for editing the specified ProductGallery.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $productGallery = $this->productGalleryRepository->find($id);

        if (empty($productGallery)) {
            Flash::error('Product Gallery not found');

            return redirect(route('productGalleries.index'));
        }

        return view('product_galleries.edit')->with('productGallery', $productGallery);
    }

    /**
     * Update the specified ProductGallery in storage.
     *
     * @param  int              $id
     * @param UpdateProductGalleryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProductGalleryRequest $request)
    {
        $productGallery = $this->productGalleryRepository->find($id);

        if (empty($productGallery)) {
            Flash::error('Product Gallery not found');

            return redirect(route('productGalleries.index'));
        }

        $productGallery = $this->productGalleryRepository->update($request->all(), $id);

        Flash::success('Product Gallery updated successfully.');

        return redirect(route('productGalleries.index'));
    }

    /**
     * Remove the specified ProductGallery from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $productGallery = $this->productGalleryRepository->find($id);

        if (empty($productGallery)) {
            Flash::error('Product Gallery not found');

            return redirect(route('productGalleries.index'));
        }

        $this->productGalleryRepository->delete($id);

        Flash::success('Product Gallery deleted successfully.');

        return redirect(route('productGalleries.index'));
    }
}

resources/views/product_galleries/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Gallery
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'productGalleries.store']) !!}

                        @include('product_galleries.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product_galleries/datatables_actions.blade.php
{!! Form::open(['route' => ['productGalleries.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('productGalleries.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('productGalleries.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/product_galleries/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Gallery
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($productGallery, ['route' => ['productGalleries.update', $productGallery->id], 'method' => 'patch']) !!}

                        @include('product_galleries.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/product_galleries/fields.blade.php
<!-- Product Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('product_id', 'Product Id:') !!}
    {!! Form::number('product_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Video Field -->
<div class="form-group col-sm-6">
    {!! Form::label('video', 'Video:') !!}
    {!! Form::text('video', null, ['class' => 'form-control']) !!}
</div>

<!-- Img Field -->
<div class="form-group col-sm-6">
    {!! Form::label('img', 'Img:') !!}
    {!! Form::text('img', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('productGalleries.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/product_galleries/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Product Galleries</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('productGalleries.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('product_galleries.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/product_galleries/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Gallery
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('product_galleries.show_fields')
                    <a href="{{ route('productGalleries.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product_galleries/show_fields.blade.php
<!-- Product Id Field -->
<div class="form-group">
    {!! Form::label('product_id', 'Product Id:') !!}
    <p>{{ $productGallery->product_id }}</p>
</div>

<!-- Video Field -->
<div class="form-group">
    {!! Form::label('video', 'Video:') !!}
    <p>{{ $productGallery->video }}</p>
</div>

<!-- Img Field -->
<div class="form-group">
    {!! Form::label('img', 'Img:') !!}
    <p>{{ $productGallery->img }}</p>
</div>

resources/views/product_galleries/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush